services:
  - type: web
    name: pruebamercadolibre
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port 3000
    healthCheckPath: /
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://bgugepseqlyffrtfkepo.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_DI0rvTq6HCmGstBpLXupeg_a2LQBwCG
      - key: VITE_EDGE_FUNCTION_URL
        value: https://bgugepseqlyffrtfkepo.supabase.co/functions/v1
      - key: VITE_MERCADOPAGO_PUBLIC_KEY
        value: TEST-37f92d37-7c4d-4215-a1a1-06de62c445c5
      - key: VITE_MERCADOPAGO_APP_ID
        value: 2995513543311110
